# Generated by Django 3.2.5 on 2021-07-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendername', models.CharField(max_length=50)),
                ('recivername', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
