# Generated by Django 3.2.5 on 2021-07-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Intern',
            new_name='Transaction',
        ),
    ]
