# Generated by Django 3.2.5 on 2021-07-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0002_rename_intern_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('mobile', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Intern',
        ),
    ]
