# Generated by Django 3.2.5 on 2021-07-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0003_auto_20210715_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intern',
            old_name='recivername',
            new_name='reciver_name',
        ),
        migrations.RenameField(
            model_name='intern',
            old_name='sendername',
            new_name='sender_name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
