# Generated by Django 3.2.5 on 2021-07-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0004_auto_20210716_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='amount',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
